using backend.Data;
using backend.DTOs;
using backend.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace backend.Controllers;

[ApiController]
[Route("api/[controller]")]
public class UserController : ControllerBase
{
    private readonly AppDbContext _context;

    public UserController(AppDbContext context)
    {
        _context = context;
    }

    // unfinished
    /// <summary>
    /// Get a user by ID
    /// </summary>
    [HttpGet("{id}")]
    public async Task<ActionResult<UserResponse>> GetUser(int id)
    {
        var user = await _context.Users.FindAsync(id);

        if (user == null)
        {
            return NotFound();
        }

        // return the user details without the password
        var response = new UserResponse
        {
            UserID = user.UserID,
            UserGivenName = user.UserGivenName,
            UserFamilyName = user.UserFamilyName,
            UserEmail = user.UserEmail,
            CreatedDateTime = user.CreatedDateTime,
        };

        return response;
    }

    /// <summary>
    /// Creates a new user
    /// </summary>
    /// <response code="201">Returns the newly created user</response>
    /// <response code="400">If the user data is invalid</response>
    [HttpPost]
    [ProducesResponseType(typeof(UserResponse), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<UserResponse>> CreateUser(CreateUserRequest request)
    {
        if (await _context.Users.AnyAsync(u => u.UserEmail == request.UserEmail))
        {
            return BadRequest("A user with this email already exists.");
        }

        // eventually check for strength of password, valid email format, etc.

        string hashedPassword = BCrypt.Net.BCrypt.HashPassword(request.UserPassword);

        var user = new User
        {
            // userid auto generated by db
            UserGivenName = request.UserGivenName,
            UserFamilyName = request.UserFamilyName,
            UserEmail = request.UserEmail,
            // set password to hashed password
            UserPassword = hashedPassword,
            CreatedDateTime = DateTime.UtcNow,
        };

        _context.Users.Add(user);
        await _context.SaveChangesAsync();

        // return the created user details without the password
        var response = new UserResponse
        {
            UserID = user.UserID,
            UserGivenName = user.UserGivenName,
            UserFamilyName = user.UserFamilyName,
            UserEmail = user.UserEmail,
            CreatedDateTime = user.CreatedDateTime,
        };

        return CreatedAtAction(nameof(GetUser), new { id = user.UserID }, response);
    }

    // endpoint to get all users
    // endpoint to update a user
    // endpoint to delete a user
}
